### ISSUE TITLE
Need of affinity attributes for data volume creation

### ISSUE THREAD

**Issue by Madhan-SWE** [IBM-Cloud/power-go-client#91]
Currently the method to create data volume doesn't have parameters to choose affinity properties of the volume to be created.
method url: https://github.com/IBM-Cloud/power-go-client/blob/master/clients/instance/ibm-pi-volume.go#L80

Need to add support to create volume with below attributes:

- AffinityPVMInstance
- AffinityPolicy
- AffinityVolume
- AntiAffinityPVMInstances
- AntiAffinityVolumes

**Comment by mkumatag** [comment]
cc @yussufsh @surajsub @surajibm

**Comment by yussufsh** [comment]
You should be using `CreateVolume` and not `Create` which is deprecated and will be removed soon.
Let me know if any issues using CreateVolume func.

**Comment by yussufsh** [comment]
I am going to close this issue as the requirement is already available.
