### ISSUE TITLE
Add support for the github.com/IBM/go-sdk-core authenticator type

### ISSUE THREAD

**Issue by mkumatag** [IBM-Cloud/power-go-client#93]
Most of the IBM Cloud clients are using the github.com/IBM/go-sdk-core authenticators for authenticating to the IBM Cloud, so even this client should start using the same package for going forward to comply with the other clients.

e.g: how to use for apikey: https://github.com/IBM/go-sdk-core/blob/main/Authentication.md#identity-and-access-management-authentication-iam

**Comment by mkumatag** [comment]
cc @yussufsh @surajibm @surajsub

**Comment by surajsub** [comment]
Good idea.
